name: Update Blog

on:
  push:
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Use Node.js
      uses: actions/setup-node@master
    - run: npm install
    - run: npm install -g hexo
    - run: hexo generate
    - run: ls -al public/
    - name: Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: "public/"
        GH_PAT: ${{ secrets.GH_PAT }}
