name: Update Blog

on:
  push:
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Use Node.js
      uses: actions/setup-node@master
    - run: hexo generator
    - name: Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: "public/"
      secrets: ["GH_PAT"]
